default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: ismail
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello-rails-backend_development
  user: postgres
  password: ismail

test:
  <<: *default
  database: hello-rails-backend_test
  user: postgres
  password: ismail

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
